# Generated by Django 3.2 on 2022-04-14 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='discription',
            field=models.TextField(max_length=255),
        ),
    ]
