# Generated by Django 3.2 on 2022-04-15 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_alter_lead_discription'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/'),
        ),
    ]
